### ISSUE TITLE
请问，对比mitie+jieba的精确度怎么样？怎么应用在rasa-nlu上？

### ISSUE THREAD

**Issue by winner484** [howl-anderson/Chinese_models_for_SpaCy#1]
感谢大神！请问，对比mitie+jieba的精确度怎么样？

**Comment by howl-anderson** [comment]
Original questions are written in Standard Mandarin (Simplified Chinese), I translated it to English, so everybody can read it.

Q1: What's the performance compared with MITIE+jieba in RASA NLU?
A1: For now (2018-05-02), I didn't do any performance compare work. But I will do the compare when this model is production ready. I will keep the community informed.

Q2: How apply this component to RASA NLU?
A2: I will write an document later for this.

**Comment by winner484** [comment]
thank you very much!
