### ISSUE TITLE
Can this model use in rasa_nlu for Chinese?

### ISSUE THREAD

**Issue by GaoQ1** [howl-anderson/Chinese_models_for_SpaCy#10]
Great pleasure to use your model. But can this model use in Rasa_nlu for Chinese?
And could you try? @howl-anderson  :)

**Comment by howl-anderson** [comment]
I tried, it works at https://github.com/Aguila-team/Chinese_NLU_by_using_RASA_NLU#spacy

**Comment by GaoQ1** [comment]
Awesome! Thanks for your work. :)
