### ISSUE TITLE
using v2.0.5 model with rasa_nlu, still have question as#2: intent ok,entities came up with nothing.

### ISSUE THREAD

**Issue by wfeidan** [howl-anderson/Chinese_models_for_SpaCy#13]
I use v2.0.5 zh model, test it in python demo, it works well.

他 他 X PRP ROOT x True True True O  15.445007 False
是 是 X VC punct x True True True O  10.924323 False
北京 北京 X NNP det xx True False True B GPE 18.310038 False
的 的 X DEC case:dec x True True True O  10.005628 False
清华大学 清华大学 X NNP obl xxxx True False True B ORG 21.960636 False
毕业 毕业 X VV ccomp xx True False True O  22.748903 False
的 的 X DEC mark:relcl x True True True O  10.005628 False

But, when try it with rasa_nlu(v0.12.3), I have same question#2: intent ok,entities came up with nothing.
My rasa_nlu config file:
language: "zh"

pipeline:
- name: "nlp_spacy"
  model: "zh"
- name: "tokenizer_jieba"
  dictionary_path: "jieba_userdict/"
- name: "ner_spacy"
- name: "ner_synonyms"
- name: "intent_entity_featurizer_regex"
- name: "intent_featurizer_spacy"
- name: "intent_classifier_sklearn"

My train data like this(part):
{
        "text": "这附近哪里有吃麻辣烫的地方",
        "intent": "restaurant_search",
        "entities": [
          {
            "start": 7,
            "end": 10,
            "value": "麻辣烫",
            "entity": "food"
          }
        ]
      }

**Comment by howl-anderson** [comment]
I will do some trails on it, if I lack some information, I will let you know.

**Comment by SunYanCN** [comment]
我也遇到了这个问题， v2.0.5 zh model，实体识别为空 @howl-anderson

**Comment by howl-anderson** [comment]
@SunYanCN @wfeidan 可能是因为 SpaCy 所使用的训练语料的问题，有些实体不支持，你们可以尝试更加常见的实体提取，比如人名机构名之类的，应该可以正常工作，如有问题欢迎反馈。

**Comment by howl-anderson** [comment]
@SunYanCN @wfeidan Chinese model for SpaCy 2.2.x already released, please feel free to try it.
