### ISSUE TITLE
关于分词的一些建议

### ISSUE THREAD

**Issue by SunYanCN** [howl-anderson/Chinese_models_for_SpaCy#14]
1. 后端可以换成jieba_fast提高性能，只需要进行简单的更改即可
2. 关闭jieba的log信息
```
import jieba
import logging
jieba.setLogLevel(logging.INFO)

**Comment by howl-anderson** [comment]
Hi @SunYanCN, sorry for the delay, the jieba maybe will not use as a default tokenizer in the future, but thanks for your suggestion.
