### ISSUE TITLE
new chinese model for spacy 2.1

### ISSUE THREAD

**Issue by marquisthunder** [howl-anderson/Chinese_models_for_SpaCy#16]
since spacy 2.1.0 is released, will it be planned for a new Chinese model release?

**Comment by howl-anderson** [comment]
Currently, no plan for update the model. If there are many users using Chinese model and spacy 2 become pretty stable, I think that's a good timing for release new one.

**Comment by rdoume** [comment]
Hello @howl-anderson , now that spacy 2.1 seems pretty stable, do you have any plan for release new models?

**Comment by howl-anderson** [comment]
@rdoume Thank you for your reminder, and I will try to find some free time (currently I am busy) to update this.

**Comment by rdoume** [comment]
Thanks. As I saw you provided most of the scripts to retrain everything, I'm trying to make it on my side, I'll share it with you if I have anything useful

**Comment by howl-anderson** [comment]
@rdoume Cool!

**Comment by chenrui2436** [comment]
ValueError: could not broadcast input array from shape (128) into shape (96)

**Comment by howl-anderson** [comment]
@chenrui2436 see this issue #23, I hope it works for you.

**Comment by howl-anderson** [comment]
Hi All, A new version for SpaCy 2.2.x will be coming soon.

**Comment by howl-anderson** [comment]
@chenrui2436 @rdoume @marquisthunder Chinese model for SpaCy 2.2.x already released, please feel free to try it.
