### ISSUE TITLE
i have tried this component with RASA NLU, it worked with intent classifitation, but can not find out entities

### ISSUE THREAD

**Issue by winner484** [howl-anderson/Chinese_models_for_SpaCy#2]
1, download the model
2, python3 -m pip install it 
3, python3 -m spacy link zh_core_web_sm zh    -- link sucessful
4 train the rasa model    --sucess
5 $ python -m rasa_nlu.server --path projects    --sucess
6 test the text 我感冒了。
the intent was good enough, but the entities came up with nothing. And i tried another texts , but the entities all came up with nothing.
please help!

**Comment by howl-anderson** [comment]
Can I have your training corpus and your training settings for RASA NLU?

**Comment by ScottishFold007** [comment]
I have the same question as winner484 ,doc.ents doesn't work

**Comment by howl-anderson** [comment]
Sorry, I replied similar question in RASA NLU project, but forget to reply this issue. @ScottishFold007 @winner484 I am still working on NER. I will keep you informed.

**Comment by ScottishFold007** [comment]
You are really great





------------------ 原始邮件 ------------------
发件人: "Xiaoquan Kong"<notifications@github.com>;
发送时间: 2018年5月7日(星期一) 中午1:53
收件人: "howl-anderson/Chinese_models_for_SpaCy"<Chinese_models_for_SpaCy@noreply.github.com>;
抄送: "高长宽"<gaochangkuan01@foxmail.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [howl-anderson/Chinese_models_for_SpaCy] i have tried thiscomponent with RASA NLU, it worked with intent classifitation, but can notfind out entities (#2)




Sorry, I replied similar question in RASA NLU project, but forget to reply this issue. @ScottishFold007 @winner484 I am still working on NER. I will keep you informed.

**Comment by howl-anderson** [comment]
@winner484 @ScottishFold007 Good News: this project is beta ready, OOV and NER issue is fixed. Welcome to try the v2.0.3 model.
