### ISSUE TITLE
OntoNotes Release 5.0

### ISSUE THREAD

**Issue by sc-lj** [howl-anderson/Chinese_models_for_SpaCy#20]
你好！我以公司的名义申请数据集，不知道怎么的，过了几天都还没有传送给我。。请问能将OntoNotes Release 5.0数据集共享一份给我吗？779365135@qq.com  不胜感激！！

**Comment by howl-anderson** [comment]
抱歉，版权材料不能分享给你，你既然已经申请，那么等等就好了，可能需要点时间审核，很快就能搞定。

**Comment by lingvisa** [comment]
howl-anderson: 请问哪里申请 OntoNote 5.0 数据集？LDC 吗？ 谢谢

**Comment by howl-anderson** [comment]
@lingvisa Yes, from LDC.
