### ISSUE TITLE
那请问下能把训练代码发我份？

### ISSUE THREAD

**Issue by xiaozw123** [howl-anderson/Chinese_models_for_SpaCy#22]
我用spacy2.2.1 没办法用这个模型，我打算自己训练模型，但是训练的时候很多问题，能把你的训练代码发我一份？

**Comment by howl-anderson** [comment]
训练所用到的所有资料都在里面了，至于怎么训练，你需要仔细阅读官方文档。

**Comment by xiaozw123** [comment]
请问下你这个依存训练花了多久训练，你觉得效果如何，你用过gluon-nlp这个？

**Comment by howl-anderson** [comment]
具体时间我已经记不清了，效果还是可以的。gluon-nlp 只听过，没用过。

**Comment by xiaozw123** [comment]
好的，谢谢
