### ISSUE TITLE
ValueError: could not broadcast input array from shape (128) into shape (96)

### ISSUE THREAD

**Issue by Mcdull0921** [howl-anderson/Chinese_models_for_SpaCy#23]
在执行这条语句`nlp = zh_core_web_sm.load()`的时候报了这个错误：
`ValueError: could not broadcast input array from shape (128) into shape (96)`
请问这个能够解决吗？

**Comment by howl-anderson** [comment]
这个问题比较棘手，有一定的随机性，建议重装环境试一试。

**Comment by Mcdull0921** [comment]
> 这个问题比较棘手，有一定的随机性，建议重装环境试一试。

好的，还是感谢您的回复。

**Comment by gaozhengjie** [comment]
> > 这个问题比较棘手，有一定的随机性，建议重装环境试一试。
> 
> 好的，还是感谢您的回复。

您好，你现在这个问题已经解决了，我重装了环境后还是不行 :)

**Comment by gaozhengjie** [comment]
我用的spacy版本是2.2.3

**Comment by Mcdull0921** [comment]
> 我用的spacy版本是2.2.3

我没有解决，我放弃了，我用了别的库pyltp，这个虽然能跑，但我发现实际上我并不需要ltp :-)

**Comment by howl-anderson** [comment]
@gaozhengjie 这个问题是 SpaCy 自己研发的框架的问题，难以处理，建议多重装几次环境，我也是这样处理的，确实没有什么好办法。

**Comment by lingvisa** [comment]
@howl-anderson 请教一下，这个问题的本质是什么？麻烦解释一下，我看能不能跟 spacy 团队反应一下。

**Comment by howl-anderson** [comment]
所需求的 SpaCy 是上一个 minor 版本了，至于为什么出错，我当时没有找到原因，否则直接打 patch 了，现在的最新版本也许已经解决，但移植到新版本的工作很繁重，短期内很难完成。
