### ISSUE TITLE
since spacy 2.1.0 is released, will it be planned for a new Chinese model release?

### ISSUE THREAD

**Issue by hbwzhsh** [howl-anderson/Chinese_models_for_SpaCy#25]
I strongly hope to use the Chinese model of Spacy 2.1. X

**Comment by hbwzhsh** [comment]
since spacy 2.1.0 is released, will it be planned for a new Chinese model release?

**Comment by hbwzhsh** [comment]
I strongly hope to use the Chinese model of Spacy 2.1. X

**Comment by howl-anderson** [comment]
@hbwzhsh A new version for SpaCy 2.2.x will be coming soon.

**Comment by howl-anderson** [comment]
@hbwzhsh Chinese model for SpaCy 2.2.x already released.

**Comment by hbwzhsh** [comment]
Thx发自我的华为手机-------- 原始邮件 --------发件人： Xiaoquan Kong <notifications@github.com>日期： 2020年3月12日周四 11:17收件人： howl-anderson/Chinese_models_for_SpaCy <Chinese_models_for_SpaCy@noreply.github.com>抄送： "jansion.wang" <mrjansion@163.com>, Mention <mention@noreply.github.com>主    题： Re: [howl-anderson/Chinese_models_for_SpaCy] since spacy 2.1.0 is released, will it be planned for a new Chinese model release? (#25)
@hbwzhsh Chinese model for SpaCy 2.2.x already released.
