### ISSUE TITLE
Do you have plan to train chinese models from wiki_zh corpus?

### ISSUE THREAD

**Issue by HCIS2020** [howl-anderson/Chinese_models_for_SpaCy#3]
Same as title

thanks.

**Comment by howl-anderson** [comment]
Actually this model was trained using Chinese Wikipedia corpus for word embedding and brown clustering. I will update the codes and documents to make it more clear, so users can train their own models from scratch.

**Comment by howl-anderson** [comment]
@HCIS2020 Just for keep you informed: for Chinese Wikipedia corpus, you can use my other project: https://github.com/howl-anderson/chinese-wikipedia-corpus-creator, it has been well tested.
