### ISSUE TITLE
Word segmentation accuracy compared to other Chinese NLP tools

### ISSUE THREAD

**Issue by ryangawei** [howl-anderson/Chinese_models_for_SpaCy#36]
How does the model perform compared to other popular tools such as jieba, pkuseg, etc.?

**Comment by howl-anderson** [comment]
The spacy model mainly contains neural networks, it uses tokenizers such as jieba or pkuseg to do the preprocess job. So they are different tools, can not be compared directly.

**Comment by ryangawei** [comment]
Thanks for your reply! Maybe my question is not clear enough. 

I run the following code,
```
import spacy
from spacy.lang.zh import Chinese

nlp1 = spacy.load("zh_core_web_sm")
nlp2 = Chinese() # jieba by default
text = "西门子将努力参与中国的三峡工程建设。"
doc1 = nlp1(text)
print('/'.join([t.text for t in doc1]))
doc2 = nlp2(text)
print('/'.join([t.text for t in doc2]))
```
The output is 
```
西门子/将/努力/参与/中国/的/三峡/工程/建设/。
西门子/将/努力/参与/中国/的/三峡工程/建设/。
```
How is word segmentation done when using `zh_core_web_sm`? Why the result looks different from jieba?

**Comment by howl-anderson** [comment]
I am not pretty sure, but I think maybe they use different custom dictionaries.

**Comment by ryangawei** [comment]
@howl-anderson Okay, thank you for your answer anyway.
