### ISSUE TITLE
Is it possible to use baidu internal chinese corpus?

### ISSUE THREAD

**Issue by HCIS2020** [howl-anderson/Chinese_models_for_SpaCy#4]
Here is the project about deepspeech(baidu ASR), it contains baidu internal chinese corpus about 70GB.

Is it possible to use this corpus to train chinese model for spacy.

https://github.com/PaddlePaddle/DeepSpeech#training-for-mandarin-language

**Comment by howl-anderson** [comment]
Thank you for your suggestion. I will do a little research on it. I will keep you informed.

**Comment by HCIS2020** [comment]
https://github.com/Embedding/Chinese-Word-Vectors

Here are Chinese word vectors, it is useful.

**Comment by howl-anderson** [comment]
@HCIS2020 Awesome! That project seems pretty useful, thanks!

**Comment by gguan** [comment]
How about this website? 
http://www.chineseldc.org/resource_list.php?begin=40&count=20

Shall we send a email and ask for needed corpus?

**Comment by howl-anderson** [comment]
@gguan Thanks, but as far as I know, this website just like LDC, we need pay for corpus downloads. Also I am not sure it's quality is as good as LDC. Don't worry about corpus, I will get a Legitimate copy of LDC very soon.

**Comment by gguan** [comment]
Cool. I would like to participate this project later as we are also developing AI voice software using rasa and will opensource ours work later.

**Comment by howl-anderson** [comment]
:+1: I am working on RASA NLU too.
